
package MyElements::getCitations;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' }

__PACKAGE__->__set_name('getCitations');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    MyTypes::getCitations
);

}

1;


=pod

=head1 NAME

MyElements::getCitations

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
getCitations from the namespace http://webservice.cdb.ebi.ac.uk/.







=head1 METHODS

=head2 new

 my $element = MyElements::getCitations->new($data);

Constructor. The following data structure may be passed to new():

 { # MyTypes::getCitations
   id =>  $some_value, # string
   source =>  $some_value, # string
   offSet =>  $some_value, # int
   email =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

