
package MyElements::profilePublications;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' }

__PACKAGE__->__set_name('profilePublications');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    MyTypes::profilePublications
);

}

1;


=pod

=head1 NAME

MyElements::profilePublications

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
profilePublications from the namespace http://webservice.cdb.ebi.ac.uk/.







=head1 METHODS

=head2 new

 my $element = MyElements::profilePublications->new($data);

Constructor. The following data structure may be passed to new():

 { # MyTypes::profilePublications
   queryString =>  $some_value, # string
   dataSet =>  $some_value, # string
   profileType =>  $some_value, # string
   synonym =>  $some_value, # boolean
   email =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

