
package MyElements::QueryException;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' }

__PACKAGE__->__set_name('QueryException');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    MyTypes::QueryException
);

}

1;


=pod

=head1 NAME

MyElements::QueryException

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
QueryException from the namespace http://webservice.cdb.ebi.ac.uk/.







=head1 METHODS

=head2 new

 my $element = MyElements::QueryException->new($data);

Constructor. The following data structure may be passed to new():

 { # MyTypes::QueryException
   message =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

