
package MyElements::searchPublications;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' }

__PACKAGE__->__set_name('searchPublications');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    MyTypes::searchPublications
);

}

1;


=pod

=head1 NAME

MyElements::searchPublications

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
searchPublications from the namespace http://webservice.cdb.ebi.ac.uk/.







=head1 METHODS

=head2 new

 my $element = MyElements::searchPublications->new($data);

Constructor. The following data structure may be passed to new():

 { # MyTypes::searchPublications
   queryString =>  $some_value, # string
   dataSet =>  $some_value, # string
   resultType =>  $some_value, # string
   offSet =>  $some_value, # int
   synonym =>  $some_value, # boolean
   email =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

