package MyTypes::authorsList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %author_of :ATTR(:get<author>);

__PACKAGE__->_factory(
    [ qw(        author

    ) ],
    {
        'author' => \%author_of,
    },
    {
        'author' => 'MyTypes::authors',
    },
    {

        'author' => 'author',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::authorsList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
authorsList from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * author




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::authorsList
   author =>  { # MyTypes::authors
     collectiveName =>  $some_value, # string
     fullName =>  $some_value, # string
     initials =>  $some_value, # string
     lastName =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

