package MyTypes::authors;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %collectiveName_of :ATTR(:get<collectiveName>);
my %fullName_of :ATTR(:get<fullName>);
my %initials_of :ATTR(:get<initials>);
my %lastName_of :ATTR(:get<lastName>);

__PACKAGE__->_factory(
    [ qw(        collectiveName
        fullName
        initials
        lastName

    ) ],
    {
        'collectiveName' => \%collectiveName_of,
        'fullName' => \%fullName_of,
        'initials' => \%initials_of,
        'lastName' => \%lastName_of,
    },
    {
        'collectiveName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'fullName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'initials' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'lastName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'collectiveName' => 'collectiveName',
        'fullName' => 'fullName',
        'initials' => 'initials',
        'lastName' => 'lastName',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::authors

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
authors from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * collectiveName


=item * fullName


=item * initials


=item * lastName




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::authors
   collectiveName =>  $some_value, # string
   fullName =>  $some_value, # string
   initials =>  $some_value, # string
   lastName =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

