package MyTypes::chemicalList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %chemical_of :ATTR(:get<chemical>);

__PACKAGE__->_factory(
    [ qw(        chemical

    ) ],
    {
        'chemical' => \%chemical_of,
    },
    {
        'chemical' => 'MyTypes::chemicalInfo',
    },
    {

        'chemical' => 'chemical',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::chemicalList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
chemicalList from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * chemical




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::chemicalList
   chemical =>  { # MyTypes::chemicalInfo
     name =>  $some_value, # string
     registryNumber =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

