package MyTypes::chemicalInfo;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %name_of :ATTR(:get<name>);
my %registryNumber_of :ATTR(:get<registryNumber>);

__PACKAGE__->_factory(
    [ qw(        name
        registryNumber

    ) ],
    {
        'name' => \%name_of,
        'registryNumber' => \%registryNumber_of,
    },
    {
        'name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'registryNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'name' => 'name',
        'registryNumber' => 'registryNumber',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::chemicalInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
chemicalInfo from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * name


=item * registryNumber




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::chemicalInfo
   name =>  $some_value, # string
   registryNumber =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

