package MyTypes::citationList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %citation_of :ATTR(:get<citation>);

__PACKAGE__->_factory(
    [ qw(        citation

    ) ],
    {
        'citation' => \%citation_of,
    },
    {
        'citation' => 'MyTypes::CitationData',
    },
    {

        'citation' => 'citation',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::citationList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
citationList from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * citation




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::citationList
   citation =>  { # MyTypes::CitationData
     id =>  $some_value, # string
     source =>  $some_value, # string
     citationType =>  $some_value, # string
     title =>  $some_value, # string
     authorString =>  $some_value, # string
     journalAbbreviation =>  $some_value, # string
     pubYear =>  $some_value, # int
     volume =>  $some_value, # string
     ISSN =>  $some_value, # string
     issue =>  $some_value, # string
     pageInfo =>  $some_value, # string
     citedByCount =>  $some_value, # int
     text =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

