package MyTypes::CitationData;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %id_of :ATTR(:get<id>);
my %source_of :ATTR(:get<source>);
my %citationType_of :ATTR(:get<citationType>);
my %title_of :ATTR(:get<title>);
my %authorString_of :ATTR(:get<authorString>);
my %journalAbbreviation_of :ATTR(:get<journalAbbreviation>);
my %pubYear_of :ATTR(:get<pubYear>);
my %volume_of :ATTR(:get<volume>);
my %ISSN_of :ATTR(:get<ISSN>);
my %issue_of :ATTR(:get<issue>);
my %pageInfo_of :ATTR(:get<pageInfo>);
my %citedByCount_of :ATTR(:get<citedByCount>);
my %text_of :ATTR(:get<text>);

__PACKAGE__->_factory(
    [ qw(        id
        source
        citationType
        title
        authorString
        journalAbbreviation
        pubYear
        volume
        ISSN
        issue
        pageInfo
        citedByCount
        text

    ) ],
    {
        'id' => \%id_of,
        'source' => \%source_of,
        'citationType' => \%citationType_of,
        'title' => \%title_of,
        'authorString' => \%authorString_of,
        'journalAbbreviation' => \%journalAbbreviation_of,
        'pubYear' => \%pubYear_of,
        'volume' => \%volume_of,
        'ISSN' => \%ISSN_of,
        'issue' => \%issue_of,
        'pageInfo' => \%pageInfo_of,
        'citedByCount' => \%citedByCount_of,
        'text' => \%text_of,
    },
    {
        'id' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'source' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'citationType' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'title' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'authorString' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'journalAbbreviation' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'pubYear' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'volume' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ISSN' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'issue' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'pageInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'citedByCount' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'text' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'id' => 'id',
        'source' => 'source',
        'citationType' => 'citationType',
        'title' => 'title',
        'authorString' => 'authorString',
        'journalAbbreviation' => 'journalAbbreviation',
        'pubYear' => 'pubYear',
        'volume' => 'volume',
        'ISSN' => 'ISSN',
        'issue' => 'issue',
        'pageInfo' => 'pageInfo',
        'citedByCount' => 'citedByCount',
        'text' => 'text',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::CitationData

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
CitationData from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * id


=item * source


=item * citationType


=item * title


=item * authorString


=item * journalAbbreviation


=item * pubYear


=item * volume


=item * ISSN


=item * issue


=item * pageInfo


=item * citedByCount


=item * text




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::CitationData
   id =>  $some_value, # string
   source =>  $some_value, # string
   citationType =>  $some_value, # string
   title =>  $some_value, # string
   authorString =>  $some_value, # string
   journalAbbreviation =>  $some_value, # string
   pubYear =>  $some_value, # int
   volume =>  $some_value, # string
   ISSN =>  $some_value, # string
   issue =>  $some_value, # string
   pageInfo =>  $some_value, # string
   citedByCount =>  $some_value, # int
   text =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

