package MyTypes::commentCorrection;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %id_of :ATTR(:get<id>);
my %source_of :ATTR(:get<source>);
my %reference_of :ATTR(:get<reference>);
my %type_of :ATTR(:get<type>);
my %note_of :ATTR(:get<note>);
my %orderIn_of :ATTR(:get<orderIn>);

__PACKAGE__->_factory(
    [ qw(        id
        source
        reference
        type
        note
        orderIn

    ) ],
    {
        'id' => \%id_of,
        'source' => \%source_of,
        'reference' => \%reference_of,
        'type' => \%type_of,
        'note' => \%note_of,
        'orderIn' => \%orderIn_of,
    },
    {
        'id' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'source' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'reference' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'type' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'note' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'orderIn' => 'SOAP::WSDL::XSD::Typelib::Builtin::short',
    },
    {

        'id' => 'id',
        'source' => 'source',
        'reference' => 'reference',
        'type' => 'type',
        'note' => 'note',
        'orderIn' => 'orderIn',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::commentCorrection

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
commentCorrection from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * id


=item * source


=item * reference


=item * type


=item * note


=item * orderIn




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::commentCorrection
   id =>  $some_value, # string
   source =>  $some_value, # string
   reference =>  $some_value, # string
   type =>  $some_value, # string
   note =>  $some_value, # string
   orderIn =>  $some_value, # short
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

