package MyTypes::commentCorrectionList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %commentCorrection_of :ATTR(:get<commentCorrection>);

__PACKAGE__->_factory(
    [ qw(        commentCorrection

    ) ],
    {
        'commentCorrection' => \%commentCorrection_of,
    },
    {
        'commentCorrection' => 'MyTypes::commentCorrection',
    },
    {

        'commentCorrection' => 'commentCorrection',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::commentCorrectionList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
commentCorrectionList from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * commentCorrection




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::commentCorrectionList
   commentCorrection =>  { # MyTypes::commentCorrection
     id =>  $some_value, # string
     source =>  $some_value, # string
     reference =>  $some_value, # string
     type =>  $some_value, # string
     note =>  $some_value, # string
     orderIn =>  $some_value, # short
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

