package MyTypes::extComment;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %extCommentSource_of :ATTR(:get<extCommentSource>);
my %info1_of :ATTR(:get<info1>);
my %info2_of :ATTR(:get<info2>);

__PACKAGE__->_factory(
    [ qw(        extCommentSource
        info1
        info2

    ) ],
    {
        'extCommentSource' => \%extCommentSource_of,
        'info1' => \%info1_of,
        'info2' => \%info2_of,
    },
    {
        'extCommentSource' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'info1' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'info2' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'extCommentSource' => 'extCommentSource',
        'info1' => 'info1',
        'info2' => 'info2',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::extComment

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
extComment from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * extCommentSource


=item * info1


=item * info2




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::extComment
   extCommentSource =>  $some_value, # string
   info1 =>  $some_value, # string
   info2 =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

