package MyTypes::fullTextUrlList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %fullTextUrl_of :ATTR(:get<fullTextUrl>);

__PACKAGE__->_factory(
    [ qw(        fullTextUrl

    ) ],
    {
        'fullTextUrl' => \%fullTextUrl_of,
    },
    {
        'fullTextUrl' => 'MyTypes::fullTextURLInfo',
    },
    {

        'fullTextUrl' => 'fullTextUrl',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::fullTextUrlList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
fullTextUrlList from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * fullTextUrl




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::fullTextUrlList
   fullTextUrl =>  { # MyTypes::fullTextURLInfo
     availability =>  $some_value, # string
     availabilityCode =>  $some_value, # string
     documentStyle =>  $some_value, # string
     site =>  $some_value, # string
     url =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

