package MyTypes::fullTextURLInfo;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %availability_of :ATTR(:get<availability>);
my %availabilityCode_of :ATTR(:get<availabilityCode>);
my %documentStyle_of :ATTR(:get<documentStyle>);
my %site_of :ATTR(:get<site>);
my %url_of :ATTR(:get<url>);

__PACKAGE__->_factory(
    [ qw(        availability
        availabilityCode
        documentStyle
        site
        url

    ) ],
    {
        'availability' => \%availability_of,
        'availabilityCode' => \%availabilityCode_of,
        'documentStyle' => \%documentStyle_of,
        'site' => \%site_of,
        'url' => \%url_of,
    },
    {
        'availability' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'availabilityCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'documentStyle' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'site' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'url' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'availability' => 'availability',
        'availabilityCode' => 'availabilityCode',
        'documentStyle' => 'documentStyle',
        'site' => 'site',
        'url' => 'url',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::fullTextURLInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
fullTextURLInfo from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * availability


=item * availabilityCode


=item * documentStyle


=item * site


=item * url




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::fullTextURLInfo
   availability =>  $some_value, # string
   availabilityCode =>  $some_value, # string
   documentStyle =>  $some_value, # string
   site =>  $some_value, # string
   url =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

