package MyTypes::getReferences;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %id_of :ATTR(:get<id>);
my %source_of :ATTR(:get<source>);
my %offSet_of :ATTR(:get<offSet>);
my %email_of :ATTR(:get<email>);

__PACKAGE__->_factory(
    [ qw(        id
        source
        offSet
        email

    ) ],
    {
        'id' => \%id_of,
        'source' => \%source_of,
        'offSet' => \%offSet_of,
        'email' => \%email_of,
    },
    {
        'id' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'source' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'offSet' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'email' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'id' => 'id',
        'source' => 'source',
        'offSet' => 'offSet',
        'email' => 'email',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::getReferences

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
getReferences from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * id


=item * source


=item * offSet


=item * email




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::getReferences
   id =>  $some_value, # string
   source =>  $some_value, # string
   offSet =>  $some_value, # int
   email =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

