package MyTypes::grantsList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %grant_of :ATTR(:get<grant>);

__PACKAGE__->_factory(
    [ qw(        grant

    ) ],
    {
        'grant' => \%grant_of,
    },
    {
        'grant' => 'MyTypes::grantInfo',
    },
    {

        'grant' => 'grant',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::grantsList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
grantsList from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * grant




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::grantsList
   grant =>  { # MyTypes::grantInfo
     grantId =>  $some_value, # string
     agency =>  $some_value, # string
     acronym =>  $some_value, # string
     orderIn =>  $some_value, # short
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

