package MyTypes::grantInfo;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %grantId_of :ATTR(:get<grantId>);
my %agency_of :ATTR(:get<agency>);
my %acronym_of :ATTR(:get<acronym>);
my %orderIn_of :ATTR(:get<orderIn>);

__PACKAGE__->_factory(
    [ qw(        grantId
        agency
        acronym
        orderIn

    ) ],
    {
        'grantId' => \%grantId_of,
        'agency' => \%agency_of,
        'acronym' => \%acronym_of,
        'orderIn' => \%orderIn_of,
    },
    {
        'grantId' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'agency' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'acronym' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'orderIn' => 'SOAP::WSDL::XSD::Typelib::Builtin::short',
    },
    {

        'grantId' => 'grantId',
        'agency' => 'agency',
        'acronym' => 'acronym',
        'orderIn' => 'orderIn',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::grantInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
grantInfo from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * grantId


=item * agency


=item * acronym


=item * orderIn




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::grantInfo
   grantId =>  $some_value, # string
   agency =>  $some_value, # string
   acronym =>  $some_value, # string
   orderIn =>  $some_value, # short
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

