package MyTypes::journal;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %title_of :ATTR(:get<title>);
my %ISOAbbreviation_of :ATTR(:get<ISOAbbreviation>);
my %medlineAbbreviation_of :ATTR(:get<medlineAbbreviation>);
my %NLMid_of :ATTR(:get<NLMid>);
my %ISSN_of :ATTR(:get<ISSN>);
my %ESSN_of :ATTR(:get<ESSN>);

__PACKAGE__->_factory(
    [ qw(        title
        ISOAbbreviation
        medlineAbbreviation
        NLMid
        ISSN
        ESSN

    ) ],
    {
        'title' => \%title_of,
        'ISOAbbreviation' => \%ISOAbbreviation_of,
        'medlineAbbreviation' => \%medlineAbbreviation_of,
        'NLMid' => \%NLMid_of,
        'ISSN' => \%ISSN_of,
        'ESSN' => \%ESSN_of,
    },
    {
        'title' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ISOAbbreviation' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'medlineAbbreviation' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'NLMid' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ISSN' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ESSN' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'title' => 'title',
        'ISOAbbreviation' => 'ISOAbbreviation',
        'medlineAbbreviation' => 'medlineAbbreviation',
        'NLMid' => 'NLMid',
        'ISSN' => 'ISSN',
        'ESSN' => 'ESSN',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::journal

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
journal from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * title


=item * ISOAbbreviation


=item * medlineAbbreviation


=item * NLMid


=item * ISSN


=item * ESSN




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::journal
   title =>  $some_value, # string
   ISOAbbreviation =>  $some_value, # string
   medlineAbbreviation =>  $some_value, # string
   NLMid =>  $some_value, # string
   ISSN =>  $some_value, # string
   ESSN =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

