package MyTypes::meshHeadingsList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %meshHeading_of :ATTR(:get<meshHeading>);

__PACKAGE__->_factory(
    [ qw(        meshHeading

    ) ],
    {
        'meshHeading' => \%meshHeading_of,
    },
    {
        'meshHeading' => 'MyTypes::meshHeadingInfo',
    },
    {

        'meshHeading' => 'meshHeading',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::meshHeadingsList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
meshHeadingsList from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * meshHeading




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::meshHeadingsList
   meshHeading =>  { # MyTypes::meshHeadingInfo
     majorTopic_YN =>  $some_value, # string
     descriptorName =>  $some_value, # string
     meshQualifierList =>  { # MyTypes::meshQualifierList
       meshQualifier =>  { # MyTypes::meshQualifierInfo
         abbreviation =>  $some_value, # string
         qualifierName =>  $some_value, # string
         majorTopic_YN =>  $some_value, # string
       },
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

