package MyTypes::meshHeadingInfo;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %majorTopic_YN_of :ATTR(:get<majorTopic_YN>);
my %descriptorName_of :ATTR(:get<descriptorName>);
my %meshQualifierList_of :ATTR(:get<meshQualifierList>);

__PACKAGE__->_factory(
    [ qw(        majorTopic_YN
        descriptorName
        meshQualifierList

    ) ],
    {
        'majorTopic_YN' => \%majorTopic_YN_of,
        'descriptorName' => \%descriptorName_of,
        'meshQualifierList' => \%meshQualifierList_of,
    },
    {
        'majorTopic_YN' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'descriptorName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'meshQualifierList' => 'MyTypes::meshQualifierList',
    },
    {

        'majorTopic_YN' => 'majorTopic_YN',
        'descriptorName' => 'descriptorName',
        'meshQualifierList' => 'meshQualifierList',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::meshHeadingInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
meshHeadingInfo from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * majorTopic_YN


=item * descriptorName


=item * meshQualifierList




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::meshHeadingInfo
   majorTopic_YN =>  $some_value, # string
   descriptorName =>  $some_value, # string
   meshQualifierList =>  { # MyTypes::meshQualifierList
     meshQualifier =>  { # MyTypes::meshQualifierInfo
       abbreviation =>  $some_value, # string
       qualifierName =>  $some_value, # string
       majorTopic_YN =>  $some_value, # string
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

