package MyTypes::meshQualifierInfo;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %abbreviation_of :ATTR(:get<abbreviation>);
my %qualifierName_of :ATTR(:get<qualifierName>);
my %majorTopic_YN_of :ATTR(:get<majorTopic_YN>);

__PACKAGE__->_factory(
    [ qw(        abbreviation
        qualifierName
        majorTopic_YN

    ) ],
    {
        'abbreviation' => \%abbreviation_of,
        'qualifierName' => \%qualifierName_of,
        'majorTopic_YN' => \%majorTopic_YN_of,
    },
    {
        'abbreviation' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'qualifierName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'majorTopic_YN' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'abbreviation' => 'abbreviation',
        'qualifierName' => 'qualifierName',
        'majorTopic_YN' => 'majorTopic_YN',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::meshQualifierInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
meshQualifierInfo from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * abbreviation


=item * qualifierName


=item * majorTopic_YN




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::meshQualifierInfo
   abbreviation =>  $some_value, # string
   qualifierName =>  $some_value, # string
   majorTopic_YN =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

