package MyTypes::minedTerms;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %name_of :ATTR(:get<name>);
my %total_of :ATTR(:get<total>);
my %tmSummary_of :ATTR(:get<tmSummary>);

__PACKAGE__->_factory(
    [ qw(        name
        total
        tmSummary

    ) ],
    {
        'name' => \%name_of,
        'total' => \%total_of,
        'tmSummary' => \%tmSummary_of,
    },
    {
        'name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'total' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'tmSummary' => 'MyTypes::minedSummary',
    },
    {

        'name' => 'name',
        'total' => 'total',
        'tmSummary' => 'tmSummary',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::minedTerms

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
minedTerms from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * name


=item * total


=item * tmSummary




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::minedTerms
   name =>  $some_value, # string
   total =>  $some_value, # int
   tmSummary =>  { # MyTypes::minedSummary
     term =>  $some_value, # string
     count =>  $some_value, # int
     altNameList =>  { # MyTypes::minedAltName
       altName =>  $some_value, # string
     },
     dbName =>  $some_value, # string
     dbIdList =>  { # MyTypes::minedDbIDs
       dbId =>  $some_value, # string
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

