package MyTypes::minedSummary;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %term_of :ATTR(:get<term>);
my %count_of :ATTR(:get<count>);
my %altNameList_of :ATTR(:get<altNameList>);
my %dbName_of :ATTR(:get<dbName>);
my %dbIdList_of :ATTR(:get<dbIdList>);

__PACKAGE__->_factory(
    [ qw(        term
        count
        altNameList
        dbName
        dbIdList

    ) ],
    {
        'term' => \%term_of,
        'count' => \%count_of,
        'altNameList' => \%altNameList_of,
        'dbName' => \%dbName_of,
        'dbIdList' => \%dbIdList_of,
    },
    {
        'term' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'count' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'altNameList' => 'MyTypes::minedAltName',
        'dbName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'dbIdList' => 'MyTypes::minedDbIDs',
    },
    {

        'term' => 'term',
        'count' => 'count',
        'altNameList' => 'altNameList',
        'dbName' => 'dbName',
        'dbIdList' => 'dbIdList',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::minedSummary

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
minedSummary from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * term


=item * count


=item * altNameList


=item * dbName


=item * dbIdList




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::minedSummary
   term =>  $some_value, # string
   count =>  $some_value, # int
   altNameList =>  { # MyTypes::minedAltName
     altName =>  $some_value, # string
   },
   dbName =>  $some_value, # string
   dbIdList =>  { # MyTypes::minedDbIDs
     dbId =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

