package MyTypes::patentPriorityList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %priority_of :ATTR(:get<priority>);

__PACKAGE__->_factory(
    [ qw(        priority

    ) ],
    {
        'priority' => \%priority_of,
    },
    {
        'priority' => 'MyTypes::patentPriorityData',
    },
    {

        'priority' => 'priority',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::patentPriorityList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
patentPriorityList from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * priority




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::patentPriorityList
   priority =>  { # MyTypes::patentPriorityData
     priorityNumber =>  $some_value, # string
     priorityDate =>  $some_value, # dateTime
     orderIn =>  $some_value, # short
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

