package MyTypes::patentApplication;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %applicationNumber_of :ATTR(:get<applicationNumber>);
my %applicationDate_of :ATTR(:get<applicationDate>);
my %orderIn_of :ATTR(:get<orderIn>);

__PACKAGE__->_factory(
    [ qw(        applicationNumber
        applicationDate
        orderIn

    ) ],
    {
        'applicationNumber' => \%applicationNumber_of,
        'applicationDate' => \%applicationDate_of,
        'orderIn' => \%orderIn_of,
    },
    {
        'applicationNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'applicationDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'orderIn' => 'SOAP::WSDL::XSD::Typelib::Builtin::short',
    },
    {

        'applicationNumber' => 'applicationNumber',
        'applicationDate' => 'applicationDate',
        'orderIn' => 'orderIn',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::patentApplication

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
patentApplication from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * applicationNumber


=item * applicationDate


=item * orderIn




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::patentApplication
   applicationNumber =>  $some_value, # string
   applicationDate =>  $some_value, # dateTime
   orderIn =>  $some_value, # short
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

