package MyTypes::patentClassifierInfo;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %classification_of :ATTR(:get<classification>);
my %classificationType_of :ATTR(:get<classificationType>);
my %hyperlink_of :ATTR(:get<hyperlink>);

__PACKAGE__->_factory(
    [ qw(        classification
        classificationType
        hyperlink

    ) ],
    {
        'classification' => \%classification_of,
        'classificationType' => \%classificationType_of,
        'hyperlink' => \%hyperlink_of,
    },
    {
        'classification' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'classificationType' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'hyperlink' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'classification' => 'classification',
        'classificationType' => 'classificationType',
        'hyperlink' => 'hyperlink',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::patentClassifierInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
patentClassifierInfo from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * classification


=item * classificationType


=item * hyperlink




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::patentClassifierInfo
   classification =>  $some_value, # string
   classificationType =>  $some_value, # string
   hyperlink =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

