package MyTypes::patentFamilyData;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %familyNumber_of :ATTR(:get<familyNumber>);
my %orderIn_of :ATTR(:get<orderIn>);

__PACKAGE__->_factory(
    [ qw(        familyNumber
        orderIn

    ) ],
    {
        'familyNumber' => \%familyNumber_of,
        'orderIn' => \%orderIn_of,
    },
    {
        'familyNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'orderIn' => 'SOAP::WSDL::XSD::Typelib::Builtin::short',
    },
    {

        'familyNumber' => 'familyNumber',
        'orderIn' => 'orderIn',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::patentFamilyData

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
patentFamilyData from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * familyNumber


=item * orderIn




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::patentFamilyData
   familyNumber =>  $some_value, # string
   orderIn =>  $some_value, # short
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

