package MyTypes::patentPriorityData;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %priorityNumber_of :ATTR(:get<priorityNumber>);
my %priorityDate_of :ATTR(:get<priorityDate>);
my %orderIn_of :ATTR(:get<orderIn>);

__PACKAGE__->_factory(
    [ qw(        priorityNumber
        priorityDate
        orderIn

    ) ],
    {
        'priorityNumber' => \%priorityNumber_of,
        'priorityDate' => \%priorityDate_of,
        'orderIn' => \%orderIn_of,
    },
    {
        'priorityNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'priorityDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'orderIn' => 'SOAP::WSDL::XSD::Typelib::Builtin::short',
    },
    {

        'priorityNumber' => 'priorityNumber',
        'priorityDate' => 'priorityDate',
        'orderIn' => 'orderIn',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::patentPriorityData

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
patentPriorityData from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * priorityNumber


=item * priorityDate


=item * orderIn




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::patentPriorityData
   priorityNumber =>  $some_value, # string
   priorityDate =>  $some_value, # dateTime
   orderIn =>  $some_value, # short
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

