package MyTypes::profilePublications;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %queryString_of :ATTR(:get<queryString>);
my %dataSet_of :ATTR(:get<dataSet>);
my %profileType_of :ATTR(:get<profileType>);
my %synonym_of :ATTR(:get<synonym>);
my %email_of :ATTR(:get<email>);

__PACKAGE__->_factory(
    [ qw(        queryString
        dataSet
        profileType
        synonym
        email

    ) ],
    {
        'queryString' => \%queryString_of,
        'dataSet' => \%dataSet_of,
        'profileType' => \%profileType_of,
        'synonym' => \%synonym_of,
        'email' => \%email_of,
    },
    {
        'queryString' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'dataSet' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'profileType' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'synonym' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
        'email' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'queryString' => 'queryString',
        'dataSet' => 'dataSet',
        'profileType' => 'profileType',
        'synonym' => 'synonym',
        'email' => 'email',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::profilePublications

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
profilePublications from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * queryString


=item * dataSet


=item * profileType


=item * synonym


=item * email




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::profilePublications
   queryString =>  $some_value, # string
   dataSet =>  $some_value, # string
   profileType =>  $some_value, # string
   synonym =>  $some_value, # boolean
   email =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

