package MyTypes::referencesList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %reference_of :ATTR(:get<reference>);

__PACKAGE__->_factory(
    [ qw(        reference

    ) ],
    {
        'reference' => \%reference_of,
    },
    {
        'reference' => 'MyTypes::referenceInfo',
    },
    {

        'reference' => 'reference',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::referencesList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
referencesList from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * reference




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::referencesList
   reference =>  { # MyTypes::referenceInfo
     id =>  $some_value, # string
     source =>  $some_value, # string
     citationType =>  $some_value, # string
     title =>  $some_value, # string
     authorString =>  $some_value, # string
     journalAbbreviation =>  $some_value, # string
     issue =>  $some_value, # string
     pubYear =>  $some_value, # int
     volume =>  $some_value, # string
     ISSN =>  $some_value, # string
     ESSN =>  $some_value, # string
     ISBN =>  $some_value, # string
     pageInfo =>  $some_value, # string
     publicationTitle =>  $some_value, # string
     publisherLoc =>  $some_value, # string
     publisherName =>  $some_value, # string
     seriesName =>  $some_value, # string
     edition =>  $some_value, # string
     editors =>  $some_value, # string
     doi =>  $some_value, # string
     unstructuredInformation =>  $some_value, # string
     externalLink =>  $some_value, # string
     comments =>  $some_value, # string
     citedOrder =>  $some_value, # int
     match =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

