package MyTypes::searchPublications;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %queryString_of :ATTR(:get<queryString>);
my %dataSet_of :ATTR(:get<dataSet>);
my %resultType_of :ATTR(:get<resultType>);
my %offSet_of :ATTR(:get<offSet>);
my %synonym_of :ATTR(:get<synonym>);
my %email_of :ATTR(:get<email>);

__PACKAGE__->_factory(
    [ qw(        queryString
        dataSet
        resultType
        offSet
        synonym
        email

    ) ],
    {
        'queryString' => \%queryString_of,
        'dataSet' => \%dataSet_of,
        'resultType' => \%resultType_of,
        'offSet' => \%offSet_of,
        'synonym' => \%synonym_of,
        'email' => \%email_of,
    },
    {
        'queryString' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'dataSet' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'resultType' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'offSet' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'synonym' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
        'email' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'queryString' => 'queryString',
        'dataSet' => 'dataSet',
        'resultType' => 'resultType',
        'offSet' => 'offSet',
        'synonym' => 'synonym',
        'email' => 'email',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::searchPublications

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
searchPublications from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * queryString


=item * dataSet


=item * resultType


=item * offSet


=item * synonym


=item * email




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::searchPublications
   queryString =>  $some_value, # string
   dataSet =>  $some_value, # string
   resultType =>  $some_value, # string
   offSet =>  $some_value, # int
   synonym =>  $some_value, # boolean
   email =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

