package MyTypes::SearchTerm;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://webservice.cdb.ebi.ac.uk/' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %term_of :ATTR(:get<term>);
my %dataSets_of :ATTR(:get<dataSets>);

__PACKAGE__->_factory(
    [ qw(        term
        dataSets

    ) ],
    {
        'term' => \%term_of,
        'dataSets' => \%dataSets_of,
    },
    {
        'term' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'dataSets' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'term' => 'term',
        'dataSets' => 'dataSets',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SearchTerm

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SearchTerm from the namespace http://webservice.cdb.ebi.ac.uk/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * term


=item * dataSets




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SearchTerm
   term =>  $some_value, # string
   dataSets =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

